/**
 * Given two strings s and t which consist of only lowercase letters. String t is generated by randomly shuffling string s and then 
 * adding one more letter at a random position. Find the letter that was added to t.
 * 
 * Example:
 * Input: s = "abcd", t = "abcde"
 * Output: e
 * Explanation: 'e' is the letter that was added.
 */

class Solution {
public:
  char findTheDifference(string s, string t) {
    if (s.empty())  return t[0];
    char out = s[0];
    for (auto it = s.begin() + 1; it != s.end(); ++it)  out ^= *it;
    for (auto const& it : t)  out ^= it;
    return out;
  }  
};
